# Generated by Django 4.0.4 on 2022-05-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jack', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='picture',
        ),
        migrations.AlterField(
            model_name='about',
            name='career',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='heading',
            field=models.CharField(max_length=100),
        ),
    ]
