# Generated by Django 4.0.4 on 2022-05-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jack', '0002_remove_home_picture_alter_about_career_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='greetings_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='home',
            name='greetings_2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='home',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
