# Generated by Django 4.0.4 on 2022-05-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jack', '0003_alter_home_greetings_1_alter_home_greetings_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='greetings_2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
